# Generated by Django 3.2.3 on 2021-05-31 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appLogin', '0003_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('likedBy', models.ManyToManyField(related_name='likes', to='appLogin.User')),
                ('uploadeBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createdThoughts', to='appLogin.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
