# Generated by Django 3.2.3 on 2021-05-30 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appLogin', '0002_user_birthdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('likedBy', models.ManyToManyField(related_name='likes', to='appLogin.User')),
                ('uploadeBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createdBooks', to='appLogin.user')),
            ],
        ),
    ]
