# Generated by Django 3.2.3 on 2021-05-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojoNinjasApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
