# Generated by Django 3.2.3 on 2021-05-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLogin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthDate',
            field=models.DateField(null=True),
        ),
    ]
