# Generated by Django 3.2.3 on 2021-05-23 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksAuthorsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='desc',
            new_name='description',
        ),
    ]
